//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotedCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VotedCandidate()
        {
            this.Voters = new HashSet<Voter>();
        }
    
        public int VotedCandidatesId { get; set; }
        public Nullable<int> VoterId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<int> ElectionId { get; set; }
        public Nullable<int> PositionId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Election Election { get; set; }
        public virtual Position Position { get; set; }
        public virtual Voter Voter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voter> Voters { get; set; }
    }
}
